# Compiler options
CXX = g++ 
CXXFLAGS = `itpp-config --cflags` -O3 -Wall -fmessage-length=0 -g

# Root folder of PSGP installation
ROOT = ../../..

INCLUDES = -I$(ROOT)/lib/xercesc/include -I$(ROOT)/libgptk
LIBS = `itpp-config --debug --libs` -L$(ROOT)/lib/xercesc/lib -L$(ROOT)/libgptk/

all: main.o
	$(CXX) $(CXXFLAGS) $(LIBS) main.o -lgptk -lxerces-c -o $(MAKE_TARGET)

main.o: main.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c main.cpp -o main.o

clean:
	rm $(MAKE_TARGET) main.o
