
LIBS = `itpp-config --libs` -L/usr/local/lib/R/lib
CXX =	g++
CXXFLAGS = -I. -I/usr/share/R/include `itpp-config --cflags` -DUSING_R=1 -O3

SRC =	astonGeostats.cpp \
	RInterface.cpp \
	gaussianProcesses/GaussianProcess.cpp \
	gaussianProcesses/PSGP.cpp \
	gaussianProcesses/ForwardModel.cpp \
	covarianceFunctions/GaussianCF.cpp \
	covarianceFunctions/ConstantCF.cpp \
	covarianceFunctions/CovarianceFunction.cpp \
	covarianceFunctions/ExponentialCF.cpp \
	covarianceFunctions/Matern3CF.cpp \
	covarianceFunctions/Matern5CF.cpp \
	covarianceFunctions/NeuralNetCF.cpp \
	covarianceFunctions/WhiteNoiseCF.cpp \
	covarianceFunctions/SumCovarianceFunction.cpp \
	covarianceFunctions/Transform.cpp \
	covarianceFunctions/LogTransform.cpp \
	covarianceFunctions/IdentityTransform.cpp \
	likelihoodModels/AnalyticLikelihood.cpp \
	likelihoodModels/LikelihoodType.cpp \
	likelihoodModels/SamplingLikelihood.cpp \
	likelihoodModels/GaussianLikelihood.cpp \
	likelihoodModels/ExponentialSampLikelihood.cpp \
	likelihoodModels/GaussianSampLikelihood.cpp \
	optimisation/Optimisable.cpp \
	optimisation/ModelTrainer.cpp \
	optimisation/SCGModelTrainer.cpp \
	itppext/itppext.cpp \
	io/csvstream.cpp


OBJS = $(SRC:.cpp=.o)

TARGET = psgp.so

$(TARGET):
	MAKEFLAGS='CXXFLAGS=\ -O3\ -DUSING_R=1\ -I.' R CMD SHLIB $(OBJS) -o $(TARGET) $(LIBS)

all: $(SRC) $(TARGET)

clean:
	rm -f $(OBJS) $(TARGET) psgp.so

